/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/base/card.vue')['default']
    DefaultHeader: typeof import('./src/components/default-layout/default-header.vue')['default']
    DefaultHomeBanner: typeof import('./src/components/default-layout/default-home-banner.vue')['default']
    DefaultSidebar: typeof import('./src/components/default-layout/default-sidebar.vue')['default']
    IMdiMenu: typeof import('~icons/mdi/menu')['default']
    IMdiThemeLightDark: typeof import('~icons/mdi/theme-light-dark')['default']
    PluginCard: typeof import('./src/components/plugin-card.vue')['default']
    PluginCardSkeleton: typeof import('./src/components/plugin-card-skeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/base/skeleton.vue')['default']
    Toggle: typeof import('./src/components/base/toggle.vue')['default']
    ToggleColor: typeof import('./src/components/base/toggle-color.vue')['default']
  }
}
